name: 'Design System: Run eslint, stylelint and prettier'

on:
    push:
        paths:
            - 'packages/design-system/**'

defaults:
    run:
        working-directory: packages/design-system

jobs:
    call-workflow-in-local-repo:
        name: Test
        uses: ./.github/workflows/reusable-test.yaml
        with:
            project-folder: packages/design-system
