name: 'Test design system and publish to chromatic'

on:
  push:
    paths:
      - "packages/design-system/**"

defaults:
  run:
    working-directory: packages/design-system

jobs:
  chromatic-deployment:
   runs-on: ubuntu-latest

   strategy:
      matrix:
        node-version: [18.x]

   steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Publish design system to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}