name: Reusable Test WorkFlow

on:
    workflow_call:
        inputs:
            project-folder:
                type: string

jobs:
    test:
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: ${{ inputs.project-folder }}

        strategy:
            matrix:
                node-version: [18.x]

        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - uses: pnpm/action-setup@v2
              with:
                  version: 7

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: pnpm

            - name: Install dependencies
              run: pnpm install

            - name: Run Prettier
              run: pnpm run prettier

            - name: Run Stylelint
              if: ${{ inputs.project-folder != 'apps/docs' }}
              run: pnpm run stylelint

            - name: Run Eslint
              if: ${{ inputs.project-folder != 'packages/styles' }}
              run: pnpm run lint
