name: 'Run stylelint and prettier'

on:
  push:
    paths:
      - "packages/styles/**"

defaults:
  run:
    working-directory: packages/styles

jobs:
    test:
        runs-on: ubuntu-latest

        strategy:
          matrix:
            node-version: [18.x]

        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
               fetch-depth: 0

            - uses: pnpm/action-setup@v2
              with:
                version: 7

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: pnpm

            - name: Install dependencies
              run: pnpm install

            - name: Run Prettier
              run: npm run prettier

            - name: Run Stylelint
              run: npm run stylelint
